/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Logic.SubjectObject;
import Logic.StudentObject;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.util.*;

/**
 * @author: Daniel Lozano
 * 
 */
public class Student extends javax.swing.JFrame {

    int studentCount = 0;
    int subjectCount = 0;
    StudentObject[] studentsList;
    SubjectObject subjectsList[];
    ArrayList<StudentObject> studentList = new ArrayList<>();
    ArrayList<SubjectObject> subjectList = new ArrayList<>();

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        Inicializar();
        dataInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGénero = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblCedula = new javax.swing.JLabel();
        lblCódigo = new javax.swing.JLabel();
        lblNombreE = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDireccióm = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblGénero = new javax.swing.JLabel();
        JtxtIdentification = new javax.swing.JTextField();
        JtxtCode = new javax.swing.JTextField();
        JtxtName = new javax.swing.JTextField();
        JtxtLastName = new javax.swing.JTextField();
        JtxtPhone = new javax.swing.JTextField();
        JtxtAdress = new javax.swing.JTextField();
        JtxtMail = new javax.swing.JTextField();
        rbtnFemale = new javax.swing.JRadioButton();
        rbtnMale = new javax.swing.JRadioButton();
        btnSaveStudent = new javax.swing.JButton();
        JbtnSearchStudent = new javax.swing.JButton();
        JbtnModifyStudent = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jpanel2 = new javax.swing.JPanel();
        lblNombreA = new javax.swing.JLabel();
        lblSemestre = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblJornada = new javax.swing.JLabel();
        JtxtSubjectName = new javax.swing.JTextField();
        JtxtSchedule = new javax.swing.JTextField();
        cmbSemester = new javax.swing.JComboBox();
        cmbJornada = new javax.swing.JComboBox();
        btnSaveSubject = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblAsignatura = new javax.swing.JLabel();
        lblEstudianteAS = new javax.swing.JLabel();
        cmbAsignSubject = new javax.swing.JComboBox();
        cmbAsignStudent = new javax.swing.JComboBox();
        btnAssign = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JtxtAreaReport = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ESTUDIANTE"));

        lblCedula.setText("CÉDULA:");

        lblCódigo.setText("CÓDIGO:");

        lblNombreE.setText("NOMBRE:");

        lblApellido.setText("APELLIDO:");

        lblTelefono.setText("TELÉFONO:");

        lblDireccióm.setText("DIRECCIÓN:");

        lblCorreo.setText("CORREO:");

        lblGénero.setText("GÉNERO:");

        JtxtIdentification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtIdentificationActionPerformed(evt);
            }
        });
        JtxtIdentification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtxtIdentificationKeyTyped(evt);
            }
        });

        JtxtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtCodeActionPerformed(evt);
            }
        });
        JtxtCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtxtCodeKeyTyped(evt);
            }
        });

        JtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtNameActionPerformed(evt);
            }
        });
        JtxtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtxtNameKeyTyped(evt);
            }
        });

        JtxtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtxtLastNameKeyTyped(evt);
            }
        });

        JtxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtPhoneActionPerformed(evt);
            }
        });
        JtxtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtxtPhoneKeyTyped(evt);
            }
        });

        JtxtAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtAdressActionPerformed(evt);
            }
        });

        rbtnGénero.add(rbtnFemale);
        rbtnFemale.setText("FEMENINO");
        rbtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemaleActionPerformed(evt);
            }
        });

        rbtnGénero.add(rbtnMale);
        rbtnMale.setText("MASCULINO");
        rbtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaleActionPerformed(evt);
            }
        });

        btnSaveStudent.setText("Guardar");
        btnSaveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveStudentActionPerformed(evt);
            }
        });

        JbtnSearchStudent.setText("Buscar");
        JbtnSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSearchStudentActionPerformed(evt);
            }
        });

        JbtnModifyStudent.setText("Modificar");
        JbtnModifyStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnModifyStudentActionPerformed(evt);
            }
        });

        jButton3.setText("Promedio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Situación académica");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCedula)
                            .addComponent(lblNombreE)
                            .addComponent(lblTelefono)
                            .addComponent(lblApellido)
                            .addComponent(lblCorreo)
                            .addComponent(lblCódigo)
                            .addComponent(lblGénero))
                        .addContainerGap(315, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDireccióm)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JbtnSearchStudent)
                                .addGap(55, 55, 55)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(JtxtMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                        .addComponent(JtxtAdress, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JtxtLastName)
                                        .addComponent(JtxtPhone)
                                        .addComponent(JtxtName)
                                        .addComponent(JtxtCode)
                                        .addComponent(JtxtIdentification))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtnFemale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JbtnModifyStudent)
                                            .addComponent(rbtnMale))))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSaveStudent)
                                .addGap(152, 152, 152))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtxtIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedula))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtxtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCódigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccióm)
                    .addComponent(JtxtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(JtxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGénero)
                    .addComponent(rbtnFemale)
                    .addComponent(rbtnMale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveStudent)
                    .addComponent(JbtnSearchStudent)
                    .addComponent(JbtnModifyStudent))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(46, 46, 46))
        );

        jpanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("ASIGNATURA"));

        lblNombreA.setText("NOMBRE:");

        lblSemestre.setText("SEMESTRE:");

        lblHorario.setText("HORARIO:");

        lblJornada.setText("JORNADA:");

        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        cmbSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSemesterActionPerformed(evt);
            }
        });

        cmbJornada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diurna", "Nocturna" }));

        btnSaveSubject.setText("Guardar");
        btnSaveSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSubjectActionPerformed(evt);
            }
        });

        jButton5.setText("Modificar");

        javax.swing.GroupLayout jpanel2Layout = new javax.swing.GroupLayout(jpanel2);
        jpanel2.setLayout(jpanel2Layout);
        jpanel2Layout.setHorizontalGroup(
            jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpanel2Layout.createSequentialGroup()
                        .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSemestre)
                            .addComponent(lblNombreA))
                        .addGap(76, 76, 76)
                        .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JtxtSubjectName)
                            .addComponent(cmbSemester, 0, 151, Short.MAX_VALUE)))
                    .addGroup(jpanel2Layout.createSequentialGroup()
                        .addComponent(lblHorario)
                        .addGap(79, 79, 79)
                        .addComponent(JtxtSchedule))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel2Layout.createSequentialGroup()
                        .addComponent(lblJornada, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addComponent(cmbJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnSaveSubject)
                .addGap(132, 132, 132))
        );
        jpanel2Layout.setVerticalGroup(
            jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreA)
                    .addComponent(JtxtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemestre)
                    .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorario)
                    .addComponent(JtxtSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJornada)
                    .addComponent(cmbJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveSubject)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("ASIGNAR"));

        lblAsignatura.setText("ASIGNATURA:");

        lblEstudianteAS.setText("ESTUDIANTE:");

        cmbAsignSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        cmbAsignSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAsignSubjectActionPerformed(evt);
            }
        });

        cmbAsignStudent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        cmbAsignStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAsignStudentActionPerformed(evt);
            }
        });

        btnAssign.setText("ASIGNAR");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAssign)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAsignatura)
                            .addComponent(lblEstudianteAS))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbAsignSubject, 0, 333, Short.MAX_VALUE)
                            .addComponent(cmbAsignStudent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsignatura)
                    .addComponent(cmbAsignSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstudianteAS)
                    .addComponent(cmbAsignStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnAssign)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("REPORTE"));

        JtxtAreaReport.setColumns(20);
        JtxtAreaReport.setRows(5);
        jScrollPane3.setViewportView(JtxtAreaReport);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExit.setText("SALIR");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void cmbAsignSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAsignSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAsignSubjectActionPerformed

    private void btnSaveSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSubjectActionPerformed
        // TODO add your handling code here:
        SaveSubject();
    }//GEN-LAST:event_btnSaveSubjectActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int subjectIndex = cmbAsignStudent.getSelectedIndex();
        int studentIndex = cmbAsignStudent.getSelectedIndex();
    }//GEN-LAST:event_btnAssignActionPerformed

    private void cmbAsignStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAsignStudentActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbAsignStudentActionPerformed

    private void btnSaveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveStudentActionPerformed
        // TODO add your handling code here:

        String emailRegex = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        String mail = JtxtMail.getText();

        if (!mail.matches(emailRegex)) {
            JOptionPane.showConfirmDialog(null, "Por favor digite un mail válido.");
        } else if (JtxtCode.getText().length() != 8) {
            JOptionPane.showConfirmDialog(null, "Por favor digite un código válido de 8 dígitos.");
        } else if (JtxtPhone.getText().length() != 10) {
            JOptionPane.showConfirmDialog(null, "Por favor digite un teléfono válido de 10 dígitos.");
        } else if (JtxtIdentification.getText().length() < 7) {
            JOptionPane.showConfirmDialog(null, "Por favor digite una identificación de entre 7 y 10 dígitos.");
        } else if (JtxtName.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Por favor digite un nombre.");
        } else if (JtxtLastName.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Por favor digite un apellido.");
        } else if (JtxtAdress.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Por favor digite una dirección.");
        } else {
            SaveStudent();
            cleanFields();     
        }
    }//GEN-LAST:event_btnSaveStudentActionPerformed

    private void rbtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMaleActionPerformed

    private void rbtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemaleActionPerformed

    private void JtxtAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtAdressActionPerformed

    private void JtxtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtPhoneKeyTyped
        int limit = 10;
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
        if (JtxtPhone.getText().length()>=limit){
                evt.consume();
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_JtxtPhoneKeyTyped

    private void JtxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtPhoneActionPerformed

    private void JtxtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtLastNameKeyTyped
        char c = evt.getKeyChar();
        if (Character.isAlphabetic(c)) {
            getToolkit().beep();
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_JtxtLastNameKeyTyped

    private void JtxtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtNameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isAlphabetic(c)) {
            getToolkit().beep();
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_JtxtNameKeyTyped

    private void JtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtNameActionPerformed

    private void JtxtCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtCodeKeyTyped
        int maxLimit = 8;
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            if (JtxtCode.getText().length()>=maxLimit){
                evt.consume();
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_JtxtCodeKeyTyped

    private void JtxtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtCodeActionPerformed

    private void JtxtIdentificationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtIdentificationKeyTyped
        // TODO add your handling code here:
        int limit = 10;
        char c = evt.getKeyChar();
        
        if (Character.isDigit(c)) {
            getToolkit().beep();
            if (JtxtIdentification.getText().length()>=limit){
                evt.consume();
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_JtxtIdentificationKeyTyped

    private void JtxtIdentificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtIdentificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtIdentificationActionPerformed

    private void cmbSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSemesterActionPerformed

    private void JbtnSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSearchStudentActionPerformed
        // TODO add your handling code here:
        //JdialogSearch.setVisible(true);
        
        long code = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el código a buscar"));
        StudentObject searchStudent = new StudentObject();
        int index = searchStudent.searchStudent(code, studentList);
        System.out.println(index);
        if (index != -1){
            generateReport(index);
        }else{
            JOptionPane.showConfirmDialog(null, "El estudiante no existe.");
        }

    }//GEN-LAST:event_JbtnSearchStudentActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void JbtnModifyStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnModifyStudentActionPerformed
        // TODO add your handling code here:
        int code = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el código del estudiante a modificar"));
        int index = getIndex(code);
        
        if (index != -1){
            generateReport(index);
        }else{
            JOptionPane.showConfirmDialog(null, "El estudiante no existe.");
        }
        
    }//GEN-LAST:event_JbtnModifyStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnModifyStudent;
    private javax.swing.JButton JbtnSearchStudent;
    private javax.swing.JTextField JtxtAdress;
    private javax.swing.JTextArea JtxtAreaReport;
    private javax.swing.JTextField JtxtCode;
    private javax.swing.JTextField JtxtIdentification;
    private javax.swing.JTextField JtxtLastName;
    private javax.swing.JTextField JtxtMail;
    private javax.swing.JTextField JtxtName;
    private javax.swing.JTextField JtxtPhone;
    private javax.swing.JTextField JtxtSchedule;
    private javax.swing.JTextField JtxtSubjectName;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSaveStudent;
    private javax.swing.JButton btnSaveSubject;
    private javax.swing.JComboBox cmbAsignStudent;
    private javax.swing.JComboBox cmbAsignSubject;
    private javax.swing.JComboBox cmbJornada;
    private javax.swing.JComboBox cmbSemester;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpanel2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblAsignatura;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCódigo;
    private javax.swing.JLabel lblDireccióm;
    private javax.swing.JLabel lblEstudianteAS;
    private javax.swing.JLabel lblGénero;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblJornada;
    private javax.swing.JLabel lblNombreA;
    private javax.swing.JLabel lblNombreE;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.ButtonGroup rbtnGénero;
    private javax.swing.JRadioButton rbtnMale;
    // End of variables declaration//GEN-END:variables
private void Inicializar() {
        for (int i = 1; i <=10;i++){
            cmbSemester.addItem(i);
        }
        cleanFields();  }

    public void dataInit() {   
        try{
        String cant = JOptionPane.showInputDialog(this, "Digite el numero de estudiantes");
        int cantInt = Integer.parseInt(cant);

        if (cant == ""){
           System.exit(0);
        }else{
            if (cantInt < 2) {
                JOptionPane.showMessageDialog(null, "El numero de estudiantes debe ser mayor o igual a 2");
                dataInit();
            }else{
                
            studentsList = new StudentObject[cantInt];
            }
        }
        String cantAsignInput = JOptionPane.showInputDialog(this, "Digite el numero de asignaturas");
        int cantAsign = Integer.parseInt(cantAsignInput);
 
        if (cantAsignInput == null){
            dataInit();
        }
        if (cantAsign < 2){
            JOptionPane.showMessageDialog(null, "El numero de asignaturas debe ser mayor o igual a 2");
            dataInit();
        }
        else{
           subjectsList = new SubjectObject[Integer.parseInt(cantAsignInput)];
        }
        
        for (int i = 0; i <= studentsList.length; i++) {
                SaveStudent();
        }
        btnSaveStudent.setEnabled(true);
        }catch(HeadlessException | NumberFormatException NumberFormatException){
            System.out.println("Exception catched!");
            int cantInt = Integer.parseInt(cant );
            do{
            String cant = JOptionPane.showInputDialog(this, "Digite el numero de estudiantes");
            
            }while(cantInt < 2 );
        }
}
    public char evaluateGender() {
        char gender = 'm';
        return gender;
    }
    public void SaveStudent() {

        StudentObject SaveStudent = new StudentObject();
        // Getters declaration
        long code = Long.parseLong(JtxtCode.getText());
        long phone = Long.parseLong(JtxtPhone.getText());
        long identification = Long.parseLong(JtxtIdentification.getText());
        String adress = JtxtAdress.getText();
        String name = JtxtName.getText();
        String lastName = JtxtLastName.getText();
        String mail = JtxtMail.getText();
        char gender = '-';
        if(rbtnFemale.isSelected()){
            gender = 'F';
        }else{
            gender = 'M';
        }
        
        // Setters declaration
        SaveStudent.setIdentification(identification);
        SaveStudent.setName(name);
        SaveStudent.setLastName(lastName);
        SaveStudent.setCode(code);
        SaveStudent.setPhone(phone);
        SaveStudent.setAdress(adress);
        SaveStudent.setMail(mail);
        SaveStudent.setGender(gender);
        // Save Student & increment counter
        boolean exists = false;
        for (StudentObject student : studentList) {
            if (student.getCode() == code || student.getIdentification() == identification) {
                exists = true;
            } else {
                exists = false;
            }
        }
        if (exists == false) {
            studentList.add(studentCount, SaveStudent);
            studentCount++;
            for (StudentObject student : studentList) {
                cmbAsignStudent.addItem(student.getName()+' '+student.getLastName());
            }
            
        } else {
            JOptionPane.showConfirmDialog(null, "El estudiante ya existe.");
        }
        
    }
    public void cleanFields(){
        JtxtCode.setText("");
        JtxtIdentification.setText("");
        JtxtName.setText("");
        JtxtLastName.setText("");
        JtxtAdress.setText("");
        JtxtMail.setText("@uniboyaca.edu.co");
        JtxtPhone.setText("");
     
    }
    public int getIndex(long code) {
        StudentObject StudentIndex = new StudentObject();
        int query = StudentIndex.searchStudent(code, studentList);
        /*
        int indexOf = 0;
        int query = -1;
        for (StudentObject student : studentList) {
            long codeComparison = student.getCode();
            long codeSearch = code;
            if (codeComparison == codeSearch) {
                query = indexOf;
            }
            indexOf++; 
        }*/
        return query;
    }
    public void generateReport(int index) {
        //JdialogReport.setVisible(true);
        StudentObject StudentReport = studentList.get(index);
        Long code = StudentReport.getCode();
        Long id = StudentReport.getIdentification();
        String name = StudentReport.getName();
        String lastName = StudentReport.getLastName();
        Long phone = StudentReport.getPhone();
        String adress = StudentReport.getAdress();
        String mail = StudentReport.getMail(); 
        char gender = StudentReport.getGender();

        //Populate TextField
        JtxtAreaReport.setText("Código: "+ code + "\nIdentificación: " + id +"\nNombre:" + name + "\nApellido: " + lastName + "\nDirección: " + adress + "\nCorreo: "+ mail + "\nGénero: "+ gender);
    }
    
    public void SaveSubject(){
        SubjectObject SaveSubject = new SubjectObject();
        // Declare Getters
        String SubjectName = JtxtSubjectName.getText();
        int semester = cmbSemester.getSelectedIndex();
        String schedule = JtxtSchedule.getText();
        String jornada = cmbJornada.getSelectedItem().toString();
        // Declare Setters
        SaveSubject.setSubjectName(SubjectName);
        SaveSubject.setSemester(semester);
        SaveSubject.setJornada(jornada);
        SaveSubject.setSchedule(schedule);

        // Save Student & increment counter

        subjectList.add(subjectCount, SaveSubject);
        subjectCount++;

        for (SubjectObject subject : subjectList) {
            cmbAsignSubject.addItem(subject.getSubjectName()+' '+subject.getSchedule());
        }

    }
}
